version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
  employee-mongo:
    image: employee-docker-mongo:latest
    container_name: employee-mongo
    ports:
      - 8080:8080
    links:
      - mymongodb